Add proper print formatting

diff --git a/aura b/aura
--- a/aura
+++ b/aura
@@ -13,7 +13,7 @@ AURDEST=${AURDEST:-$XDG_CACHE_HOME/aurutils/sync}
 LOCAL_GIT_REPO_PATH="$HOME/dev/arch-repos"
 GIT_REMOTE_BRANCH="origin/master"
 
-S3_CONFIG_DIR="/home/kenc/.mcli"
+S3_CONFIG_DIR="$HOME/.mcli"
 S3_CMD="mcli --config-dir=$S3_CONFIG_DIR --no-color --quiet"
 S3_ALIAS="minio"
 BUCKET="$S3_ALIAS/aur"
@@ -23,7 +23,7 @@ if [[ "$EUID" == 0 ]]; then
     exit 1
 fi
 
-DEPENDENCIES=(aur mcli paccache)
+DEPENDENCIES=(aur mcli paccache git)
 for i in "${DEPENDENCIES[@]}"; do
     if ! command -v "$i" >/dev/null 2>&1; then
         echo -e "ERROR: \"$i\" not installed!"
@@ -248,22 +248,29 @@ case $subcommand in
 
 # Adapted from:  https://github.com/aurutils/aurutils/issues/1103
 "build")
-    git -C "$LOCAL_GIT_REPO_PATH" fetch
+    if ! [[ -d $LOCAL_GIT_REPO_PATH ]]; then
+        echo -e "ERROR: \"$LOCAL_GIT_REPO_PATH\" does not exist!"
+        exit 1
+    fi
+
+    GIT_CMD="git -C $LOCAL_GIT_REPO_PATH"
+    $GIT_CMD fetch
 
     # check which packages were modified upstream
     to_update=()
     for pkg in "$LOCAL_GIT_REPO_PATH"/repos/*; do
-        git -C "$LOCAL_GIT_REPO_PATH" diff --quiet HEAD "$GIT_REMOTE_BRANCH" -- "$pkg" || to_update+=("$pkg")
+        $GIT_CMD diff --quiet HEAD "$GIT_REMOTE_BRANCH" -- "$pkg" || to_update+=("$pkg")
     done
 
-    # merge upstream
-    git -C "$LOCAL_GIT_REPO_PATH" merge "$GIT_REMOTE_BRANCH"
+    $GIT_CMD merge "$GIT_REMOTE_BRANCH"
 
     # run aur-build in parent directory
     if ((${#to_update[@]})); then
-        # FIXME proper formatting
-        # TODO test with multiple to_update packages
-        echo "Updating git packages: ${to_update[*]}"
+        printf "Updating git packages in %s:\n" "$LOCAL_GIT_REPO_PATH"
+        for pkg in "${to_update[@]}"; do
+            printf '\t%s\n' "$(basename $pkg)"
+        done
+
         aur build \
             --chroot \
             --pacman-conf=/etc/pacman-chroot.conf \
